### ISSUE TITLE
Navigation between events/note types in 1.0

### ISSUE THREAD

**Issue by PL-mods** [MobilePorting/FNF-PsychEngine-Mobile#231] opened 2024-11-03 00:14 UTC
### Describe your bug here.

Entering the chart editor everything works fine, I just can't navigate between the events I have. In the old versions it was just a matter of dragging up or down. I've tried everything and I believe I'm a Bug

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by tposejank** [comment] 2024-11-03 01:15
Duplicate of #228

**Closed by tposejank** 2024-11-03 01:15 UTC
Labels: bug

**Comment by Contra-Sakar** [comment] 2024-11-03 01:31
:[
