### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by kviks** [MobilePorting/FNF-PsychEngine-Mobile#124] opened 2024-05-18 17:59 UTC
### Describe your problem here.

i'll try to build in github with actions 0.7.3 source code
but
source/mobile/backend/SUtil.hx:179: characters 65-86 : Class<android.Permissions> has no field READ_EXTERNAL_STORAGE
source/mobile/backend/SUtil.hx:179: characters 149-171 : Class<android.Permissions> has no field WRITE_EXTERNAL_STORAGE
source/mobile/backend/SUtil.hx:181: characters 66-87 : Class<android.Permissions> has no field READ_EXTERNAL_STORAGE

source/mobile/backend/SUtil.hx:182: characters 66-88 : Class<android.Permissions> has no field WRITE_EXTERNAL_STORAGE
source/mobile/backend/SUtil.hx:182: characters 133-155 : Class<android.Permissions> has no field WRITE_EXTERNAL_STORAGE

what  i need to make to fix that?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i'll try to fix that but nothing work

**Comment by moxie-coder** [comment] 2024-05-18 18:40
duplicate of #117

**Closed by moxie-coder** 2024-05-18 18:40 UTC
Labels: help wanted
