### ISSUE TITLE
Song doesn't load after cutscene plays

### ISSUE THREAD

**Issue by JacksonTheSkylanderDude67** [MobilePorting/FNF-PsychEngine-Mobile#225] opened 2024-10-24 18:54 UTC
### Describe your bug here.

When I use a cutscene lua script it'll start the video but after it finishes the song never plays.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment] 2024-10-24 18:55
duplicate of https://github.com/MobilePorting/FNF-PsychEngine-Mobile/issues/216

**Closed by mcagabe19** 2024-10-24 18:55 UTC
Labels: bug

**Comment by JacksonTheSkylanderDude67** [comment] 2024-10-24 18:58
How is it a duplicate? I am having the same problem as that person in issue 216.
