### ISSUE TITLE
Keyboard not showing up

### ISSUE THREAD

**Issue by LuizFelipePlay** [MobilePorting/FNF-PsychEngine-Mobile#59] opened 2024-01-15 14:28 UTC
### Describe your bug here.

Bassically in any editor we use the keyboard for type song names spritesheet names but keyboard now showing (dialogue editor works) but fix this

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment] 2024-01-15 14:29
duplicate of https://github.com/MobilePorting/FNF-PsychEngine-Mobile/issues/58

**Closed by mcagabe19** 2024-01-15 14:29 UTC
Labels: bug

**Comment by Stefan2008Git** [comment] 2024-02-11 00:05
> duplicate of #58

LMFAO. He is 11 years old :skull:
