### ISSUE TITLE
Game gets frozen after cutsenes

### ISSUE THREAD

**Issue by tktegon** [MobilePorting/FNF-PsychEngine-Mobile#240] opened 2024-12-03 03:49 UTC
### Describe your bug here.

Basically, I started Weekend 1 and saw the whole cutscene, but then my screen turned black (maybe just a fade out in the video) and the week didn't start, there was no song, no notes, just black.

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Which psych engine version you're on?

1.0 (Final)

### Did you edit anything in this build? If so, mention or summarize your changes.

O didn't edit anything

**Comment by moxie-coder** [comment] 2024-12-03 05:22
duplicate of #223

**Closed by moxie-coder** 2024-12-03 05:22 UTC
Labels: bug
